<?php
require __DIR__.'/server/bootstrap.php';require __DIR__.'/server/commerce.php';require __DIR__.'/server/catalog.php';$admin=require_admin();
$from=$_GET['from']??'';$to=$_GET['to']??'';
foreach([$from,$to] as $date)if(!is_string($date)||($date!==''&&(!preg_match('/^\d{4}-\d{2}-\d{2}$/D',$date)||date('Y-m-d',strtotime($date))!==$date))){http_response_code(422);exit('Tanggal tidak valid.');}
if($from&&$to&&$from>$to){http_response_code(422);exit('Rentang tanggal tidak valid.');}
$sql='SELECT order_no,created_at,status,payment_status,subtotal,shipping,customer_json FROM dwa_orders WHERE 1=1';$params=[];if($from){$sql.=' AND created_at>=?';$params[]=$from.' 00:00:00';}if($to){$sql.=' AND created_at<=?';$params[]=$to.' 23:59:59';}$sql.=' ORDER BY id DESC';$q=db()->prepare($sql);$q->execute($params);$csv=($_GET['format']??'html')==='csv';$headers=['Nomor pesanan','Tanggal','Client','WhatsApp','Status pesanan','Pembayaran','Subtotal','Ongkir','Total'];
if($csv){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="Rekap-DWA.csv"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['DWA BUSSINES - PT DRAJAT WIGUNA ADIDAYA'],',','"','');fputcsv($out,['customerservice@dwabussines.com','0882000119208','Instagram @dwalegalitas','Jl. Raya Sukatani, RT.021 RW006, KP.CIKADU, Kec. Sukatani, Kabupaten Purwakarta, Jawa Barat 41167'],',','"','');fputcsv($out,$headers,',','"','');}
else{header('Content-Disposition: attachment; filename="Rekap-DWA.html"');document_start('REKAP PESANAN');echo '<p>Periode: '.e($from?:'Awal').' s.d. '.e($to?:'Sekarang').'</p><table><thead><tr>';foreach($headers as $h)echo '<th>'.e($h).'</th>';echo '</tr></thead><tbody>';}
while($o=$q->fetch()){$c=json_decode($o['customer_json'],true);$row=[$o['order_no'],$o['created_at'],$c['recipient'],$c['phone'],order_status($o['status']),$o['payment_status'],$o['subtotal'],$o['shipping']??'Belum dikonfirmasi',$o['shipping']===null?'Belum final':(int)$o['subtotal']+(int)$o['shipping']];if($csv){$row=array_map(fn($v)=>preg_match('/^[\s]*[=+@\-]/u',(string)$v)?"'".$v:$v,$row);fputcsv($out,$row,',','"','');}else{echo '<tr>';foreach($row as $v)echo '<td>'.e((string)$v).'</td>';echo '</tr>';}}
if(!$csv)echo '</tbody></table><p>Rekap internal DWA. Buka dokumen di browser lalu Cetak → Simpan sebagai PDF bila diperlukan.</p></body></html>';
