<?php
require __DIR__.'/server/bootstrap.php';$user=require_user();require __DIR__.'/server/catalog.php';require __DIR__.'/server/shop-layout.php';
$cart=shop_cart();if(!$cart){header('Location: cart.php');exit;}
$methods=['bank'=>'Transfer Bank BRI','qris'=>'QRIS (menunggu konfirmasi tim DWA)','virtual'=>'Virtual Account (menunggu konfirmasi tim DWA)'];
$fields=['recipient'=>'Nama penerima','phone'=>'Nomor WhatsApp penerima','address'=>'Alamat lengkap','village'=>'Kelurahan / desa','district'=>'Kecamatan','city'=>'Kota / kabupaten','province'=>'Provinsi','postal'=>'Kode pos','note'=>'Catatan pengiriman'];
$values=$_SESSION['checkout_draft']??['recipient'=>$user['name'],'phone'=>$user['whatsapp']??''];$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!is_string($_POST['csrf']??null)||!hash_equals($_SESSION['csrf'],$_POST['csrf'])){$errors[]='Sesi berubah. Muat ulang halaman lalu coba lagi.';http_response_code(403);}
    $values=[];
    foreach($fields as $key=>$label){$v=$_POST[$key]??'';$values[$key]=is_string($v)?trim($v):'';if($key!=='note' && $values[$key]==='')$errors[]=$label.' wajib diisi.';if(strlen($values[$key])>($key==='address'||$key==='note'?600:160))$errors[]=$label.' terlalu panjang.';}
    $values['payment']=is_string($_POST['payment']??null)?$_POST['payment']:'';
    if(!isset($methods[$values['payment']]))$errors[]='Pilih preferensi pembayaran.';
    if(!phone($values['phone']))$errors[]='Nomor WhatsApp harus menggunakan nomor Indonesia yang valid.';
    if(!preg_match('/^[0-9]{5}$/D',$values['postal']))$errors[]='Kode pos harus 5 angka.';
    if(!$errors){$_SESSION['checkout_draft']=$values;header('Location: checkout.php?review=1');exit;}
}
$review=isset($_GET['review']) && isset($_SESSION['checkout_draft']) && !$errors;
$total=0;$lines=[];foreach($cart as $row){$amount=$row['product']['price']*$row['qty'];$total+=$amount;$lines[]=$row['product']['name'].' × '.$row['qty'].' — '.rupiah($amount);}
shop_header($review?'Tinjau permintaan':'Checkout',$user);
?>
<a class="back" href="<?=$review?'checkout.php':'cart.php'?>">← <?=$review?'Ubah alamat / pembayaran':'Kembali ke keranjang'?></a><span class="eyebrow">LANGKAH <?=$review?'03 / TINJAU PERMINTAAN':'02 / ALAMAT & PEMBAYARAN'?></span><h1><?=$review?'Satu langkah lagi.':'Ke mana dokumen dikirim?'?></h1>
<?php if($errors): ?><div class="form-errors" role="alert"><ul><?php foreach($errors as $error): ?><li><?=e($error)?></li><?php endforeach ?></ul></div><?php endif ?>
<?php if($review):
$message="Halo DWA, saya ingin mengajukan pesanan:\n".implode("\n",$lines)."\nSubtotal layanan: ".rupiah($total)."\nOngkir: menunggu konfirmasi\n\nPenerima: ".$values['recipient']."\nWhatsApp: ".$values['phone']."\nAlamat: ".$values['address'].', '.$values['village'].', '.$values['district'].', '.$values['city'].', '.$values['province'].' '.$values['postal']."\nPreferensi pembayaran: ".$methods[$values['payment']]."\nCatatan: ".$values['note']."\n\nMohon konfirmasi total biaya dan instruksi pembayaran. Saya memahami bahwa bukti pembayaran wajib dikonfirmasi melalui WhatsApp.";
?>
<div class="checkout-layout"><section class="form-panel"><h2>Alamat pengiriman dokumen</h2><strong><?=e($values['recipient'])?></strong><p><?=e($values['phone'])?></p><p><?=nl2br(e($values['address']))?><br><?=e($values['village'].', '.$values['district'].', '.$values['city'].', '.$values['province'].' '.$values['postal'])?></p><?php if($values['note']): ?><p>Catatan: <?=e($values['note'])?></p><?php endif ?><h2>Preferensi pembayaran</h2><p><?=e($methods[$values['payment']])?></p><?php if($values['payment']==='bank'): ?><div class="notice"><strong>Transfer Bank BRI</strong><p>Nomor rekening: <strong style="overflow-wrap:anywhere">4355-0104-0248530</strong><br>A/N <strong>PT DRAJAT WIGUNA ADIDAYA</strong></p><p>Transfer setelah total akhir dan ongkir dikonfirmasi tim DWA.</p><p><strong>Wajib konfirmasi bukti pembayaran.</strong> Kirim bukti transfer melalui WhatsApp layanan DWA. Pembayaran diverifikasi secara manual oleh tim DWA.</p><a class="button small" href="https://wa.me/62882000119208?text=Saya%20ingin%20konfirmasi%20pembayaran%20pesanan%20DWA%20melalui%20Bank%20BRI.%20Saya%20akan%20melampirkan%20bukti%20transfer.">Konfirmasi bukti pembayaran ↗</a><p><small>Lampirkan foto atau berkas bukti transfer di WhatsApp sebelum mengirim pesan.</small></p></div><?php endif ?><div class="notice">Belum ada pembayaran atau pesanan terkonfirmasi. Kirim permintaan ke tim DWA untuk konfirmasi ongkir, total akhir, dan instruksi pembayaran.</div></section><aside class="summary"><h2>Ringkasan permintaan</h2><?php foreach($lines as $line): ?><p><?=e($line)?></p><?php endforeach ?><div><span>Subtotal layanan</span><strong><?=rupiah($total)?></strong></div><p>Ongkir belum termasuk.</p><a class="button full" href="https://wa.me/62882000119208?text=<?=rawurlencode($message)?>">Lanjut konfirmasi via WhatsApp ↗</a><small>Nama, nomor kontak, alamat, dan rincian pilihan Anda akan dibuka sebagai draf pesan WhatsApp ke DWA. Tekan Kirim di WhatsApp untuk mengirimkannya.</small></aside></div>
<?php else: ?><form method="post" action="checkout.php" class="checkout-layout"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><section class="form-panel"><h2>Alamat penerima</h2><p>Gunakan alamat yang dapat menerima pengiriman dokumen.</p><div class="form-grid"><?php foreach($fields as $key=>$label): ?><label class="<?=$key==='address'||$key==='note'?'wide':''?>"><?=e($label)?><?=$key==='note'?' (opsional)':''?><?php if($key==='address'||$key==='note'): ?><textarea name="<?=$key?>" rows="3" maxlength="600" <?=$key==='address'?'required':''?>><?=e($values[$key]??'')?></textarea><?php else: ?><input name="<?=$key?>" value="<?=e($values[$key]??'')?>" required maxlength="<?=$key==='postal'?'5':'160'?>" <?=$key==='phone'?'type="tel" autocomplete="tel"':($key==='postal'?'inputmode="numeric" pattern="[0-9]{5}" autocomplete="postal-code"':'type="text"')?> ><?php endif ?></label><?php endforeach ?></div><fieldset class="payment-methods"><legend>Pilihan pembayaran</legend><p>Pilih preferensi Anda. Ketersediaan dan petunjuk pembayaran dikonfirmasi tim DWA.</p><?php foreach($methods as $key=>$label): ?><label class="payment-option"><input type="radio" name="payment" value="<?=$key?>" required <?=($values['payment']??'')===$key?'checked':''?>><span><?=e($label)?></span></label><?php endforeach ?><div class="notice"><strong>Transfer Bank BRI</strong><p>Nomor rekening: <strong style="overflow-wrap:anywhere">4355-0104-0248530</strong><br>A/N <strong>PT DRAJAT WIGUNA ADIDAYA</strong></p><p>Transfer setelah total akhir dan ongkir dikonfirmasi tim DWA.</p><p><strong>Wajib konfirmasi bukti pembayaran.</strong> Kirim bukti transfer melalui WhatsApp layanan DWA. Pembayaran diverifikasi secara manual oleh tim DWA.</p><a class="button small" href="https://wa.me/62882000119208?text=Saya%20ingin%20konfirmasi%20pembayaran%20pesanan%20DWA%20melalui%20Bank%20BRI.%20Saya%20akan%20melampirkan%20bukti%20transfer.">Konfirmasi bukti pembayaran ↗</a><p><small>Lampirkan foto atau berkas bukti transfer di WhatsApp sebelum mengirim pesan.</small></p></div></fieldset></section><aside class="summary"><h2>Ringkasan belanja</h2><?php foreach($lines as $line): ?><p><?=e($line)?></p><?php endforeach ?><div><span>Subtotal layanan</span><strong><?=rupiah($total)?></strong></div><p>Ongkir dikonfirmasi sesuai alamat. Belum ada penagihan pada langkah ini.</p><button class="button full" type="submit">Tinjau permintaan →</button><small>Alamat disimpan sementara dalam sesi akun. Permintaan baru diterima tim DWA setelah Anda mengirimkannya melalui WhatsApp.</small></aside></form><?php endif ?>
<?php shop_footer(); ?>
