<?php
require __DIR__.'/server/bootstrap.php';require __DIR__.'/server/commerce.php';require __DIR__.'/server/catalog.php';require __DIR__.'/server/passwords.php';$admin=require_admin();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_admin_post();$p=db();try{
 $action=$_POST['action']??'';
 if($action==='price'){
  $id=(string)($_POST['product']??'');$products=catalog();if(!isset($products[$id]))throw new RuntimeException('Produk tidak ditemukan.');
  $price=money_input(trim((string)($_POST['price']??'')),true);$old=money_input(trim((string)($_POST['old_price']??'')),true);
  if($old!==null&&($price===null||$old<=$price))throw new RuntimeException('Harga normal harus lebih tinggi daripada harga jual.');
  $p->beginTransaction();$q=$p->prepare('INSERT INTO dwa_prices(product_id,price,old_price) VALUES (?,?,?) ON DUPLICATE KEY UPDATE price=VALUES(price),old_price=VALUES(old_price)');$q->execute([$id,$price,$old]);audit_admin($admin['id'],'price',json_encode([$id,$price,$old]));$p->commit();
 }elseif($action==='reset'){
  $id=(int)($_POST['user_id']??0);$q=$p->prepare('SELECT email FROM dwa_users WHERE id=?');$q->execute([$id]);$email=$q->fetchColumn();if(!$email||strtolower($email)==='ciptaniagateramini@gmail.com')throw new RuntimeException('Reset ini hanya untuk akun client.');
  ensure_credentials();$hash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);$version=bin2hex(random_bytes(32));$p->beginTransaction();
  $q=$p->prepare('INSERT INTO dwa_credentials(user_id,password_hash,session_version) VALUES (?,?,?) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),session_version=VALUES(session_version)');$q->execute([$id,$hash,$version]);$q=$p->prepare('UPDATE dwa_otp SET consumed=1 WHERE email=?');$q->execute([$email]);audit_admin($admin['id'],'reset-client',(string)$id);$p->commit();
 }elseif(in_array($action,['verify','process','complete'],true)){
  $id=(int)($_POST['order_id']??0);$p->beginTransaction();$q=$p->prepare('SELECT * FROM dwa_orders WHERE id=? FOR UPDATE');$q->execute([$id]);$order=$q->fetch();if(!$order)throw new RuntimeException('Pesanan tidak ditemukan.');$next=order_transition($order,$action);
  if($action==='verify'){$shipping=money_input(trim((string)($_POST['shipping']??'')));$reference=trim((string)($_POST['reference']??''));if(strlen($reference)<3||strlen($reference)>200||($_POST['proof_checked']??'')!=='yes')throw new RuntimeException('Isi referensi bukti dan konfirmasi bukti pembayaran telah diperiksa.');$q=$p->prepare('UPDATE dwa_orders SET shipping=?,payment_status=\'verified\',status=?,payment_reference=?,verified_by=?,verified_at=NOW() WHERE id=?');$q->execute([$shipping,$next,$reference,$admin['id'],$id]);}
  else{$q=$p->prepare('UPDATE dwa_orders SET status=? WHERE id=?');$q->execute([$next,$id]);}
  audit_admin($admin['id'],$action,(string)$id);$p->commit();
 }else throw new RuntimeException('Aksi tidak dikenal.');
 header('Location: kelola-dwa.php?done='.rawurlencode($action));exit;
 }catch(Throwable $ex){if($p->inTransaction())$p->rollBack();$error=$ex instanceof RuntimeException && !$ex instanceof PDOException?$ex->getMessage():'Perubahan gagal disimpan. Silakan coba kembali.';}
}
$accounts=(int)db()->query('SELECT COUNT(*) FROM dwa_users')->fetchColumn();$stats=db()->query("SELECT COUNT(*) total,COALESCE(SUM(status='processing'),0) processing,COALESCE(SUM(status='completed'),0) completed,COALESCE(SUM(CASE WHEN payment_status='verified' THEN subtotal+COALESCE(shipping,0) ELSE 0 END),0) revenue FROM dwa_orders")->fetch();
$page=max(1,min(100000,(int)($_GET['page']??1)));$offset=($page-1)*25;$orders=db()->query('SELECT * FROM dwa_orders ORDER BY id DESC LIMIT 25 OFFSET '.$offset)->fetchAll();
$search=trim((string)($_GET['search']??''));$q=db()->prepare('SELECT id,name,email,whatsapp FROM dwa_users WHERE email LIKE ? OR name LIKE ? ORDER BY id DESC LIMIT 50');$q->execute(['%'.$search.'%','%'.$search.'%']);$users=$q->fetchAll();$products=catalog();
$q=db()->prepare('SELECT a.user_id,a.items_json FROM dwa_cart_activity a JOIN dwa_users u ON u.id=a.user_id WHERE a.expires_at>? AND LOWER(u.email)<>?');$q->execute([time(),'ciptaniagateramini@gmail.com']);$cartStats=cart_activity_summary($products,$q->fetchAll());
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="csrf-token" content="<?=e($_SESSION['csrf'])?>"><title>Admin DWA</title><link rel="stylesheet" href="shop.css"><link rel="stylesheet" href="admin.css"><script src="shop.js" defer></script></head><body><header class="shop-header"><a class="brand" href="kelola-dwa.php">DWA<span>ADMINISTRATION</span></a><nav><a href="#orders">Pesanan</a><a href="admin-products.php">Produk</a><a href="#prices">Harga</a><a href="#clients">Client</a><button id="logout">Keluar</button></nav></header><main class="shop-main"><div id="shop-status" role="status"></div><span class="eyebrow">PUSAT KENDALI DWA</span><h1>Ringkasan bisnis.</h1><?php if($error): ?><p class="notice" role="alert"><?=e($error)?></p><?php endif ?><?php if(isset($_GET['done'])): ?><p class="notice" role="status"><?=($_GET['done']==='reset')?'Sandi dan sesi lama client telah dibatalkan. Client perlu membuka Lupa kata sandi untuk menerima OTP dan membuat sandi baru.':'Perubahan berhasil disimpan.'?></p><?php endif ?><section class="metrics"><?php foreach(['Akun terdaftar'=>$accounts,'Produk di keranjang'=>$cartStats['total'],'Client dengan keranjang'=>$cartStats['clients'],'Total pesanan'=>$stats['total'],'Diproses'=>$stats['processing'],'Selesai'=>$stats['completed'],'Pembayaran terverifikasi'=>rupiah((int)$stats['revenue'])] as $label=>$value): ?><article><span><?=e($label)?></span><strong><?=e((string)$value)?></strong></article><?php endforeach ?></section>
<section class="admin-panel" id="cart-summary"><h2>Produk dalam keranjang client</h2><p>Jumlah unit yang belum checkout dalam sesi client yang belum kedaluwarsa. Diperbarui saat halaman ini dimuat ulang. Keranjang lama tercatat ketika client membuka kembali halaman belanja.</p><?php if(!$cartStats['products']): ?><p>Belum ada produk dalam keranjang aktif.</p><?php endif ?><?php foreach($cartStats['products'] as $id=>$qty): ?><div class="client-row"><strong><?=e($products[$id]['name'])?></strong><span class="badge"><?=(int)$qty?> unit</span></div><?php endforeach ?></section>
<section class="admin-panel"><h2>Unduh rekapan</h2><form action="admin-export.php" method="get" class="admin-inline"><label>Dari tanggal<input type="date" name="from"></label><label>Sampai tanggal<input type="date" name="to"></label><label>Format<select name="format"><option value="html">Dokumen berlogo (.html / cetak PDF)</option><option value="csv">Data spreadsheet (.csv)</option></select></label><button class="button">Unduh rekap</button></form><p>Rekap berdasarkan tanggal checkout. Dokumen HTML memuat logo dan detail DWA; CSV untuk pengolahan data.</p></section>
<section class="admin-panel" id="orders"><h2>Pesanan client</h2><?php if(!$orders): ?><p>Belum ada pesanan tersimpan.</p><?php endif ?><?php foreach($orders as $o): $c=json_decode($o['customer_json'],true);$items=json_decode($o['items_json'],true);?><article class="admin-order"><div class="order-head"><h3><?=e($o['order_no'])?></h3><span class="badge"><?=e(order_status($o['status']))?></span></div><p><?=e($c['recipient'])?> · <?=e($c['phone'])?> · <?=e($o['created_at'])?></p><p><?=e($c['address'].', '.$c['village'].', '.$c['district'].', '.$c['city'].', '.$c['province'].' '.$c['postal'])?></p><?php foreach($items as $item): ?><p><?=e($item['name'])?> × <?=(int)$item['qty']?> — <?=rupiah($item['price']*$item['qty'])?></p><?php endforeach ?><strong>Subtotal <?=rupiah((int)$o['subtotal'])?> · Ongkir <?=$o['shipping']===null?'belum ditetapkan':rupiah((int)$o['shipping'])?></strong><p>Pembayaran: <?=e($o['payment_method'])?> / <?=e($o['payment_status']==='verified'?'Terverifikasi':'Menunggu verifikasi')?></p><?php if($c['note']): ?><p>Catatan: <?=e($c['note'])?></p><?php endif ?>
<form method="post" class="admin-inline"><?php csrf_form();?><input type="hidden" name="order_id" value="<?=$o['id']?>"><?php if($o['payment_status']==='pending'): ?><input type="hidden" name="action" value="verify"><label>Ongkir final (Rp)<input name="shipping" type="number" min="0" max="1000000000" required></label><label>Referensi bukti / transaksi<input name="reference" maxlength="200" minlength="3" required></label><label class="admin-check"><input type="checkbox" name="proof_checked" value="yes" required>Saya sudah memeriksa bukti dan pembayaran penuh, termasuk ongkir.</label><button class="button">Verifikasi pembayaran & proses</button><?php else: ?><input type="hidden" name="action" value="<?=$o['status']==='processing'?'complete':'process'?>"><button class="button"><?=$o['status']==='processing'?'Tandai selesai':'Proses kembali'?></button><a class="button secondary" href="order-document.php?id=<?=$o['id']?>">Unduh surat pesanan</a><p>Referensi: <?=e($o['payment_reference'])?> · <?=e($o['verified_at'])?></p><?php endif ?></form></article><?php endforeach ?><div class="admin-inline"><?php if($page>1): ?><a href="?page=<?=$page-1?>#orders">← Sebelumnya</a><?php endif ?><?php if($offset+25<$stats['total']): ?><a href="?page=<?=$page+1?>#orders">Berikutnya →</a><?php endif ?></div></section>
<section class="admin-panel" id="prices"><h2>Ubah harga manual</h2><p>Harga baru berlaku pada checkout berikutnya. Pesanan yang sudah tersimpan mempertahankan harga semula. Kosongkan harga jual untuk layanan penawaran.</p><?php foreach($products as $id=>$product): ?><form method="post" class="price-row"><?php csrf_form();?><input type="hidden" name="action" value="price"><input type="hidden" name="product" value="<?=e($id)?>"><strong><?=e($product['name'])?></strong><label>Harga jual (Rp)<input name="price" type="number" min="0" max="1000000000" value="<?=$product['price']??''?>"></label><label>Harga normal / coret<input name="old_price" type="number" min="0" max="1000000000" value="<?=$product['old_price']??''?>"></label><button class="button">Simpan harga</button></form><?php endforeach ?></section>
<section class="admin-panel" id="clients"><h2>Akun client</h2><form method="get" class="admin-inline"><label>Cari nama/email<input name="search" maxlength="254" value="<?=e($search)?>"></label><button class="button">Cari</button></form><p>Menampilkan maksimal 50 akun. Reset membatalkan sandi/sesi lama; client membuat sandi baru melalui OTP email di Lupa kata sandi.</p><?php foreach($users as $u): ?><div class="client-row"><div><strong><?=e($u['name'])?></strong><p><?=e($u['email'])?></p></div><?php if(!is_admin($u)): ?><form method="post"><?php csrf_form();?><input type="hidden" name="action" value="reset"><input type="hidden" name="user_id" value="<?=$u['id']?>"><label class="admin-check"><input type="checkbox" required>Saya konfirmasi reset akun ini</label><button class="button secondary">Reset sandi client</button></form><?php endif ?></div><?php endforeach ?></section></main></body></html>
