<?php
require __DIR__.'/server/bootstrap.php';$user=require_user();require __DIR__.'/server/commerce.php';require __DIR__.'/server/catalog.php';ensure_commerce();
$q=db()->prepare('SELECT * FROM dwa_orders WHERE id=?');$q->execute([(int)($_GET['id']??0)]);$o=$q->fetch();
if(!$o||(!is_admin($user)&&(int)$o['user_id']!==(int)$user['id'])){http_response_code(404);exit('Dokumen tidak ditemukan.');}
if($o['payment_status']!=='verified'){http_response_code(403);exit('Surat tersedia setelah pembayaran diverifikasi admin.');}
header('Content-Disposition: attachment; filename="Surat-Pesanan-'.$o['order_no'].'.html"');document_start('SURAT PESANAN','order-document');$c=json_decode($o['customer_json'],true);
?><style>
*{box-sizing:border-box}.order-document{max-width:720px;margin:16px auto;padding:18px;font-size:13px;line-height:1.5;overflow-wrap:anywhere}.order-document h1{font-size:21px;margin:18px 0 12px}.order-document h2{font-size:15px;margin:14px 0 7px}.order-document p{margin:8px 0}.order-document .doc-brand{gap:12px;padding-bottom:12px;align-items:flex-start}.order-document .doc-brand img{width:44px;height:44px;flex:0 0 44px}.order-document .doc-brand h2{font-size:17px;margin:0}.order-document .doc-brand strong{font-size:11px}.order-document .doc-brand p{font-size:10px;line-height:1.4}.shipping-parties{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:14px 0}.shipping-parties section{padding:12px;border:1px solid #eadcde;border-radius:7px}.shipping-parties h2{margin:0 0 8px}.shipping-parties p{margin:0;font-size:12px}.order-document table{margin:16px 0;font-size:12px}.order-document th,.order-document td{padding:8px}.order-document small{font-size:10px;display:block}.order-document td p{font-size:11px}
@media screen and (max-width:540px){.order-document{margin:0;padding:14px;font-size:13px}.shipping-parties{grid-template-columns:1fr;gap:8px}.order-document table,.order-document tbody,.order-document tr,.order-document td{display:block;width:100%}.order-document thead{display:none}.order-document tr{border:1px solid #dfcbd0;border-radius:7px;margin-bottom:10px;overflow:hidden}.order-document td{border:0;border-bottom:1px solid #f1e8ea;padding:8px 10px}.order-document td:last-child{border-bottom:0}.order-document td[data-label]{display:flex;justify-content:space-between;gap:16px}.order-document td[data-label]:before{content:attr(data-label);color:#766267;font-size:11px}.order-document td:first-child{background:#fcf7f8}.order-document .doc-brand p{font-size:10px}.order-document h1{font-size:19px}}
@media print{.order-document{max-width:none;margin:0;padding:0;font-size:10px}.order-document table{font-size:10px}.order-document h1{font-size:17px}.shipping-parties{break-inside:avoid}.shipping-parties p{font-size:10px}.order-document small{font-size:9px}}
</style><p><strong>Nomor: <?=e($o['order_no'])?></strong><br>Tanggal checkout: <?=e($o['created_at'])?><br>Verifikasi pembayaran: <?=e($o['verified_at'])?><br>Status: <?=e(order_status($o['status']))?></p><div class="shipping-parties"><section><h2>Pengirim</h2><p><strong>PT DRAJAT WIGUNA ADIDAYA</strong><br>DWA Bussines<br>Jl. Raya Sukatani, RT.021 RW006, KP.CIKADU, Kec. Sukatani, Kabupaten Purwakarta, Jawa Barat 41167<br>WhatsApp: 0882000119208</p></section><section><h2>Penerima / alamat pengiriman</h2><p><?=e($c['recipient'])?><br>WhatsApp: <?=e($c['phone'])?><br><?=e($c['address'].', '.$c['village'].', '.$c['district'].', '.$c['city'].', '.$c['province'].' '.$c['postal'])?></p></section></div><table><thead><tr><th>Layanan / kelengkapan</th><th>Jumlah</th><th>Harga satuan</th><th>Subtotal</th></tr></thead><tbody><?php foreach(json_decode($o['items_json'],true) as $i): ?><tr><td><strong><?=e($i['name'])?></strong><?php if($i['includes']): ?><p><?=e(implode(', ',$i['includes']))?></p><?php endif ?><?php if($i['bonuses']): ?><p>Bonus: <?=e(implode(', ',$i['bonuses']))?></p><?php endif ?></td><td data-label="Jumlah"><?=(int)$i['qty']?></td><td data-label="Harga satuan"><?=rupiah($i['price'])?></td><td data-label="Subtotal"><?=rupiah($i['price']*$i['qty'])?></td></tr><?php endforeach ?></tbody></table><p>Subtotal layanan: <?=rupiah((int)$o['subtotal'])?><br>Ongkir: <?=rupiah((int)$o['shipping'])?><br><strong>Total terverifikasi: <?=rupiah((int)$o['subtotal']+(int)$o['shipping'])?></strong></p><p>Metode pembayaran: <?=e($o['payment_method'])?><br>Referensi bukti pembayaran: <?=e($o['payment_reference'])?><br>Pembayaran diverifikasi manual oleh admin DWA.</p><p>Catatan pemesan: <?=e($c['note']?:'—')?></p><hr><p>PT Drajat Wiguna Adidaya · DWA Bussines<br>Bank BRI 4355-0104-0248530 · A/N PT DRAJAT WIGUNA ADIDAYA</p><small>Dokumen ini adalah ringkasan pesanan terverifikasi, bukan faktur pajak. Buka di browser dan pilih Cetak → Simpan sebagai PDF untuk menyimpan versi PDF.</small></body></html>
