<?php
require __DIR__.'/server/bootstrap.php';
if (current_user()) {header('Location: dashboard.php');exit;}
$ready=configured();
?><!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#b71828"><meta name="csrf-token" content="<?=e($_SESSION['csrf'])?>"><title>Daftar & Masuk — DWA Bussines</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="portal.css"><link rel="icon" href="icons/app-192.png"><link rel="apple-touch-icon" href="icons/app-192.png"><script src="portal.js" defer></script></head>
<body class="portal-page"><header class="portal-header"><a class="brand" href="index.html"><strong>DWA<span>■</span></strong><small>BUSSINES</small></a><a class="back-home" href="index.html">Kembali ke beranda ↗</a></header><main class="portal-layout"><section class="portal-story"><span class="eyebrow">SATU AKUN. SELURUH LAYANAN DWA.</span><h1>Langkah bisnismu,<br><em>mulai dari sini.</em></h1><p>Temukan layanan legalitas, pengembangan UMKM, website, aplikasi, dan software manajemen dalam satu dashboard.</p><div class="portal-benefits"><div><b>01</b><span>Daftar dengan email aktif</span></div><div><b>02</b><span>Verifikasi kode OTP di email</span></div><div><b>03</b><span>Akses layanan & pasang web app DWA</span></div></div><div class="portal-signature">DWA BUSSINES<span>PT Drajat Wiguna Adidaya</span></div></section>
<section class="account-card" aria-labelledby="account-title"><div class="account-tabs" role="group" aria-label="Pilih daftar atau masuk"><button type="button" data-mode="register" aria-pressed="true">Buat akun</button><button type="button" data-mode="login" aria-pressed="false">Masuk</button></div><h2 id="account-title">Selamat datang di DWA.</h2><p class="account-description">Gunakan email aktif untuk menerima kode verifikasi.</p>
<?php if(!$ready): ?><div class="service-notice" role="status"><strong>Portal sedang disiapkan.</strong><p>Pendaftaran dan login akan tersedia setelah layanan email diaktifkan. Untuk sementara, <a href="https://wa.me/62882000119208" target="_blank" rel="noopener">hubungi tim DWA</a>.</p></div><?php endif ?>
<form id="account-form" data-ready="<?=$ready?'true':'false'?>"><fieldset <?=$ready?'':'disabled'?>><div data-register><label for="full-name">Nama lengkap</label><input id="full-name" name="name" autocomplete="name" maxlength="100" required placeholder="Nama Anda"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" maxlength="254" required placeholder="nama@email.com"><label for="whatsapp">Nomor WhatsApp <span>(opsional)</span></label><input id="whatsapp" name="whatsapp" type="tel" autocomplete="tel" maxlength="22" placeholder="08… atau +62…"><p class="field-note">Nomor ini dapat dipakai untuk login. OTP selalu dikirim ke email Anda.</p><label class="consent"><input type="checkbox" id="consent" required><span>Saya menyetujui penggunaan nama, email, dan nomor WhatsApp untuk akun serta layanan DWA. <a href="privasi.html" target="_blank" rel="noopener">Informasi privasi</a></span></label></div><div data-login hidden><label for="identifier">Email atau nomor WhatsApp</label><input id="identifier" name="identifier" autocomplete="username" maxlength="254" disabled placeholder="Email atau nomor yang terdaftar"><p class="field-note">Kode masuk dikirim ke email yang terhubung dengan akun Anda.</p></div><button class="button auth-submit" type="submit">Kirim OTP ke email <span>↗</span></button></fieldset></form>
<form id="otp-form" hidden><p class="otp-instruction">Jika data memenuhi syarat, kode telah dikirim ke email akun Anda. Periksa inbox dan folder spam.</p><label for="otp">Kode OTP</label><input id="otp" name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" minlength="6" required placeholder="000000"><p class="field-note">Kode berlaku 10 menit dan hanya dapat dipakai sekali.</p><button class="button auth-submit" type="submit">Verifikasi & masuk <span>↗</span></button><div class="otp-actions"><button type="button" id="resend" disabled>Kirim ulang (60 dtk)</button><button type="button" id="change-data">Ubah data</button></div></form><p id="auth-status" role="status" aria-live="polite"></p><p class="security-note">Jangan bagikan kode OTP kepada siapa pun, termasuk pihak yang mengaku sebagai tim DWA.</p></section></main><footer class="portal-footer">© <?=date('Y')?> DWA Bussines · <a href="privasi.html">Privasi akun</a></footer></body></html>
