'use strict';
const form=document.querySelector('#account-form'),otpForm=document.querySelector('#otp-form'),statusBox=document.querySelector('#auth-status'),csrf=document.querySelector('meta[name="csrf-token"]').content;
let mode='login',challenge='',lastPayload=null,waiting=false,availableAt=0,timer;
function status(message){statusBox.textContent=message;}
function group(selector,show){const el=document.querySelector(selector);el.hidden=!show;el.querySelectorAll('input').forEach(input=>input.disabled=!show);}
function changeMode(next){if(waiting)return;mode=next;challenge='';lastPayload=null;otpForm.reset();form.reset();otpForm.hidden=true;form.hidden=false;group('[data-register]',mode==='register');group('[data-identifier]',mode!=='register');group('[data-password]',mode!=='reset');group('[data-confirm]',mode==='register');document.querySelector('#password').autocomplete=mode==='register'?'new-password':'current-password';document.querySelector('#password').minLength=mode==='register'?10:1;document.querySelector('#password-note').hidden=mode!=='register';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.querySelector('#account-title').textContent=mode==='login'?'Selamat datang kembali.':mode==='register'?'Buat akun DWA.':'Reset kata sandi.';document.querySelector('#account-description').textContent=mode==='login'?'Gunakan email/WhatsApp dan kata sandi Anda.':mode==='register'?'Buat kata sandi, lalu verifikasi email Anda dengan OTP.':'Akun lama juga dapat membuat kata sandi di sini. OTP dikirim ke email terdaftar.';document.querySelector('#submit-account').textContent=mode==='login'?'Masuk ↗':'Kirim OTP ke email ↗';status('');}
async function request(payload){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);try{const response=await fetch('api/auth.php',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload),signal:controller.signal});const body=await response.json();if(!response.ok)throw Error(body.error||'Permintaan gagal.');return body;}catch(error){if(error.name==='AbortError')throw Error('Koneksi terlalu lama. Tunggu sebelum mencoba lagi.');if(error instanceof SyntaxError)throw Error('Layanan belum tersedia. Coba kembali nanti.');throw error;}finally{clearTimeout(timeout);}}
function busy(value){waiting=value;document.querySelectorAll('.auth-submit,[data-mode],#change-data').forEach(b=>b.disabled=value);document.querySelector('#resend').disabled=value||Date.now()<availableAt;}
function cooldown(){clearInterval(timer);availableAt=Date.now()+60000;function tick(){const left=Math.max(0,Math.ceil((availableAt-Date.now())/1000));const b=document.querySelector('#resend');b.disabled=left>0||waiting;b.textContent=left?`Kirim ulang (${left} dtk)`:'Kirim ulang kode';if(!left)clearInterval(timer);}tick();timer=setInterval(tick,1000);}
async function send(payload){busy(true);status(mode==='login'?'Memeriksa akun…':'Menyiapkan kode verifikasi…');try{const body=await request(payload);if(payload.action==='login'){form.reset();location.replace(body.redirect);return;}challenge=body.challenge;lastPayload=payload;form.hidden=true;otpForm.hidden=false;group('#reset-password-fields',mode==='reset');document.querySelector('#verify-button').textContent=mode==='reset'?'Simpan kata sandi baru ↗':'Verifikasi & masuk ↗';document.querySelector('#otp').value='';status(body.message);cooldown();document.querySelector('#otp').focus();}catch(error){status(error.message);}finally{busy(false);}}
form.addEventListener('submit',event=>{event.preventDefault();if(waiting)return;const payload={action:mode==='login'?'login':'request',mode,destination:new URLSearchParams(location.search).get('next')==='admin'?'admin':'client'};if(mode==='register'){if(form.elements.password.value!==document.querySelector('#confirm-password').value){status('Konfirmasi kata sandi tidak sama.');return;}Object.assign(payload,{name:form.elements.name.value.trim(),email:form.elements.email.value.trim(),whatsapp:form.elements.whatsapp.value.trim(),consent:document.querySelector('#consent').checked,password:form.elements.password.value});}else{payload.identifier=form.elements.identifier.value.trim();if(mode==='login')payload.password=form.elements.password.value;}send(payload);});
otpForm.addEventListener('submit',async event=>{event.preventDefault();if(waiting)return;const payload={action:'verify',challenge,code:document.querySelector('#otp').value.trim()};if(mode==='reset'){payload.password=document.querySelector('#new-password').value;if(payload.password!==document.querySelector('#new-password-confirm').value){status('Konfirmasi kata sandi tidak sama.');return;}}busy(true);try{const result=await request(payload);lastPayload=null;form.reset();otpForm.reset();location.replace(result.redirect);}catch(error){status(error.message);}finally{busy(false);}});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>changeMode(b.dataset.mode)));
document.querySelector('#resend').addEventListener('click',()=>{if(!waiting&&Date.now()>=availableAt&&lastPayload)send(lastPayload);});document.querySelector('#change-data').addEventListener('click',()=>changeMode(mode));
