'use strict';
const statusBox=document.querySelector('#shop-status');
function notify(message){statusBox.textContent=message;statusBox.classList.toggle('visible',Boolean(message));}
async function post(url,data){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{method:'POST',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{'Content-Type':'application/json','X-CSRF-Token':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify(data)});if(response.status===401){location.assign('portal.php');throw Error('Silakan masuk kembali.');}const result=await response.json();if(!response.ok)throw Error(result.error||'Permintaan gagal.');return result;}finally{clearTimeout(timer);}}
document.querySelectorAll('[data-add],[data-remove],[data-quantity]').forEach(control=>{control.addEventListener(control.matches('select')?'change':'click',async()=>{control.disabled=true;try{const id=control.dataset.add||control.dataset.remove||control.dataset.quantity;const result=await post('api/cart.php',{id,action:control.dataset.add?'add':'set',qty:control.dataset.remove?0:Number(control.value)});document.querySelector('#cart-count').textContent=result.count;if(control.dataset.add)notify('Produk ditambahkan. Buka Keranjang untuk checkout.');else location.reload();}catch(error){notify(error.name==='AbortError'?'Koneksi terputus. Buka keranjang untuk melihat status sebelum mencoba kembali.':error.message);}finally{control.disabled=false;}});});
let category='Semua';const search=document.querySelector('#product-search');
function filter(){let visible=0;document.querySelectorAll('.product-card').forEach(card=>{const match=(category==='Semua'||card.dataset.category===category)&&card.dataset.name.toLowerCase().includes((search?.value||'').toLowerCase().trim());card.hidden=!match;if(match)visible++;});const empty=document.querySelector('#search-empty');if(empty)empty.hidden=visible>0;}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));filter();}));search?.addEventListener('input',filter);
document.querySelector('#logout')?.addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await post('api/auth.php',{action:'logout'});location.replace('portal.php');}catch{notify('Belum dapat keluar. Periksa koneksi lalu coba lagi.');event.target.disabled=false;}});
const installButton=document.querySelector('#install-app'),installStatus=document.querySelector('#install-status');let installPrompt;
if(installButton){if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{installStatus.textContent='Pasang melalui menu browser jika tersedia.';});if(matchMedia('(display-mode: standalone)').matches||navigator.standalone===true){installButton.hidden=true;installStatus.textContent='Web app sudah dibuka dari layar utama.';}window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});window.addEventListener('appinstalled',()=>{installButton.hidden=true;installStatus.textContent='Web app berhasil dipasang.';});installButton.addEventListener('click',async()=>{if(installPrompt){try{await installPrompt.prompt();await installPrompt.userChoice;}catch{document.querySelector('#install-help').hidden=false;}finally{installPrompt=null;}}else document.querySelector('#install-help').hidden=false;});}
window.addEventListener('pageshow',event=>{if(event.persisted)location.reload();});

