CREATE TABLE IF NOT EXISTS dwa_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 whatsapp VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NULL UNIQUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 verified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dwa_otp (
 id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 session_hash CHAR(64) NOT NULL,
 email VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 name VARCHAR(100) NOT NULL,
 whatsapp VARCHAR(20) NULL,
 otp_hash CHAR(64) NOT NULL,
 eligible TINYINT NOT NULL DEFAULT 0,
 attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
 expires_at BIGINT NOT NULL,
 consumed TINYINT NOT NULL DEFAULT 0,
 INDEX otp_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dwa_limits (
 bucket CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
 hits INT UNSIGNED NOT NULL,
 expires_at BIGINT NOT NULL,
 INDEX limits_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
