const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{spawn,spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),php=path.resolve(process.argv[2]),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'dwa-admin-'));let server,count=0;
function ok(value,label){if(!value)throw Error(label);count++;}
(async()=>{try{
const files=['kelola-dwa.php','admin-export.php','create-order.php','orders.php','order-document.php','checkout.php','dashboard.php','cart.php','product.php','portal.php','api/auth.php','server/bootstrap.php','server/catalog.php','server/commerce.php','server/passwords.php','server/shop-layout.php'];
for(const f of files){const r=spawnSync(php,['-l',path.join(root,f)],{encoding:'utf8'});ok(r.status===0,'Syntax '+f+': '+r.stdout+r.stderr);fs.mkdirSync(path.dirname(path.join(tmp,f)),{recursive:true});fs.copyFileSync(path.join(root,f),path.join(tmp,f));}
ok(spawnSync(process.execPath,['--check',path.join(root,'portal.js')]).status===0,'Portal JS');
fs.mkdirSync(path.join(tmp,'icons'));fs.copyFileSync(path.join(root,'icons/app-192.png'),path.join(tmp,'icons/app-192.png'));
const database=path.join(tmp,'test.sqlite').replaceAll('\\','/');const extension=path.join(path.dirname(php),'ext/php_pdo_sqlite.dll');
let boot=fs.readFileSync(path.join(tmp,'server/bootstrap.php'),'utf8');const start=boot.indexOf('function db(): PDO'),end=boot.indexOf('function e(',start);
boot=boot.slice(0,start)+`class TestPDO extends PDO {public function exec(string $sql): int|false {if(str_starts_with($sql,'CREATE TABLE'))return 0;return parent::exec($sql);}public function prepare(string $sql,array $options=[]):PDOStatement|false {$sql=str_replace(' FOR UPDATE','',$sql);if(str_contains($sql,'ON DUPLICATE KEY')){$key=str_contains($sql,'dwa_prices')?'product_id':'user_id';$sql=str_replace('ON DUPLICATE KEY UPDATE','ON CONFLICT('.$key.') DO UPDATE SET',$sql);$sql=preg_replace('/VALUES\\((\\w+)\\)/','excluded.$1',$sql);}return parent::prepare($sql,$options);}}
function db(): PDO {static $p;if(!$p){$p=new TestPDO('sqlite:${database}');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$p->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$p->sqliteCreateFunction('NOW',fn()=>date('Y-m-d H:i:s'));}return $p;}
`+boot.slice(end);fs.writeFileSync(path.join(tmp,'server/bootstrap.php'),boot);
const a=crypto.randomBytes(20).toString('hex'),c=crypto.randomBytes(20).toString('hex'),other=crypto.randomBytes(20).toString('hex'),csrf=crypto.randomBytes(32).toString('hex');
const seed=`<?php $p=new PDO('sqlite:${database}');$p->exec("CREATE TABLE dwa_users(id INTEGER PRIMARY KEY,name TEXT,email TEXT,whatsapp TEXT);CREATE TABLE dwa_credentials(user_id INTEGER PRIMARY KEY,password_hash TEXT,session_version TEXT);CREATE TABLE dwa_prices(product_id TEXT PRIMARY KEY,price INTEGER,old_price INTEGER);CREATE TABLE dwa_orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE,user_id INTEGER,checkout_key TEXT UNIQUE,customer_json TEXT,items_json TEXT,subtotal INTEGER,shipping INTEGER,payment_method TEXT,payment_status TEXT DEFAULT 'pending',status TEXT DEFAULT 'pending',payment_reference TEXT,verified_by INTEGER,verified_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT);CREATE TABLE dwa_audit(id INTEGER PRIMARY KEY,admin_id INTEGER,action TEXT,detail TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE dwa_otp(email TEXT,consumed INTEGER);");foreach([[1,'Admin','ciptaniagateramini@gmail.com','${a}'],[2,'Client','client@example.test','${c}'],[3,'Other','other@example.test','${other}']] as [$id,$name,$email,$sid]){$p->prepare('INSERT INTO dwa_users VALUES (?,?,?,NULL)')->execute([$id,$name,$email]);$p->prepare('INSERT INTO dwa_credentials VALUES (?,?,?)')->execute([$id,password_hash('LongPassword123!',PASSWORD_DEFAULT),'version']);session_name('DWA_SESSION');session_id($sid);session_start();$_SESSION=['user'=>['id'=>$id,'name'=>$name,'email'=>$email,'whatsapp'=>null],'auth_version'=>'version','expires'=>time()+3600,'csrf'=>'${csrf}'];if($id===2)$_SESSION['shop_cart']=['pt-perorangan'=>1];session_write_close();}`;
fs.writeFileSync(path.join(tmp,'seed.php'),seed);let r=spawnSync(php,['-d','extension='+extension,'-d','session.save_path='+tmp,path.join(tmp,'seed.php')],{encoding:'utf8'});ok(r.status===0,'Seed '+r.stderr);
server=spawn(php,['-d','extension='+extension,'-d','session.save_path='+tmp,'-S','127.0.0.1:4189','-t',tmp],{stdio:['ignore','ignore','pipe']});await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Server start timeout')),8000);server.stderr.on('data',b=>{if(b.toString().includes('Development Server')){clearTimeout(t);resolve();}});server.on('error',reject);});
async function get(url,sid=c){return fetch('http://127.0.0.1:4189/'+url,{redirect:'manual',headers:{Cookie:'DWA_SESSION='+sid}});}
async function post(url,data,sid=c){return fetch('http://127.0.0.1:4189/'+url,{redirect:'manual',method:'POST',headers:{Cookie:'DWA_SESSION='+sid},body:new URLSearchParams({csrf,...data})});}
ok((await get('kelola-dwa.php')).status===403,'Client denied admin');ok((await get('admin-export.php')).status===403,'Client denied export');ok((await get('kelola-dwa.php',a)).status===200,'Admin dashboard');
ok((await post('kelola-dwa.php',{action:'price',product:'pt-perorangan',price:'1200000',old_price:'2500000',csrf:'bad'},a)).status===403,'CSRF guard');
ok((await post('kelola-dwa.php',{action:'price',product:'pt-perorangan',price:'1200000',old_price:'2500000'},a)).status===302,'Save price');ok((await(await get('dashboard.php')).text()).includes('Rp1.200.000'),'Live catalogue price');
const address={recipient:'=Test Client',phone:'081234567890',address:'Jalan Contoh',village:'Desa',district:'Kecamatan',city:'Bandung',province:'Jawa Barat',postal:'40111',note:'<script>bad</script>',payment:'bank'};
ok((await post('checkout.php',address)).status===302,'Checkout address');let html=await(await get('checkout.php?review=1')).text();let key=html.match(/name="checkout_key" value="([a-f0-9]+)"/)[1];
await post('kelola-dwa.php',{action:'price',product:'pt-perorangan',price:'1300000',old_price:'2500000'},a);ok((await post('create-order.php',{checkout_key:key})).status===409,'Changed price rejected');
html=await(await get('checkout.php?review=1')).text();key=html.match(/name="checkout_key" value="([a-f0-9]+)"/)[1];r=await post('create-order.php',{checkout_key:key});ok(r.status===302,'Create order');const id=new URL('http://test/'+r.headers.get('location')).searchParams.get('id');r=await post('create-order.php',{checkout_key:key});ok(r.headers.get('location')==='orders.php?id='+id,'Idempotent checkout');
ok((await get('order-document.php?id='+id)).status===403,'Unverified letter blocked');ok((await get('order-document.php?id='+id,other)).status===404,'Other client denied');
await post('kelola-dwa.php',{action:'complete',order_id:id},a);html=await(await get('orders.php')).text();ok(html.includes('Menunggu verifikasi'),'Cannot complete unpaid order');
await post('kelola-dwa.php',{action:'verify',order_id:id,shipping:'20000',reference:'BRI-TEST'},a);ok((await get('order-document.php?id='+id)).status===403,'Proof confirmation required');
ok((await post('kelola-dwa.php',{action:'verify',order_id:id,shipping:'20000',reference:'BRI-TEST',proof_checked:'yes'},a)).status===302,'Manual verification');
r=await get('order-document.php?id='+id);html=await r.text();ok(r.status===200&&r.headers.get('content-disposition').includes('attachment'),'Letter download');ok(html.includes('data:image/png;base64,')&&html.includes('PT DRAJAT WIGUNA ADIDAYA'),'Document branding');ok(html.includes('&lt;script&gt;bad&lt;/script&gt;'),'Document escaping');ok(html.includes('Rp1.320.000'),'Verified total');
await post('kelola-dwa.php',{action:'price',product:'pt-perorangan',price:'1500000',old_price:'2500000'},a);html=await(await get('order-document.php?id='+id)).text();ok(html.includes('Rp1.300.000')&&!html.includes('Rp1.500.000'),'Historic price retained');
ok((await post('kelola-dwa.php',{action:'complete',order_id:id},a)).status===302,'Mark completed');ok((await(await get('orders.php')).text()).includes('Selesai'),'Client sees completed');
html=await(await get('admin-export.php?format=csv',a)).text();ok(html.includes("'=Test Client"),'CSV formula protection');ok((await get('admin-export.php?from=notdate',a)).status===422,'Export date validation');
ok((await post('kelola-dwa.php',{action:'reset',user_id:'2'},a)).status===302,'Admin reset');ok((await get('orders.php')).headers.get('location')==='portal.php','Reset revokes session');
console.log('PASS: '+count+' checks in one final run. Isolated SQLite compatibility fixture; production MySQL, email, and live deployment not tested.');
}finally{if(server){server.kill();await new Promise(resolve=>{server.once('exit',resolve);setTimeout(resolve,1000);});}fs.rmSync(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e.message);process.exitCode=1;});
